### ISSUE TITLE
bad interpreter: /bin/env: no such file or directory

### ISSUE THREAD

**Issue by matthewjablack** [jaonoctus/nip06-cli#11]
On mac `/bin/env` shebang does not exist by default, however `/usr/bin/env` does.

Installing on mac results in `bad interpreter: /bin/env: no such file or directory` error

Perhaps it'd be better to switch https://github.com/jaonoctus/nip06-cli/blob/master/src/index.ts#L1 from `#!/bin/env node` to `#!/usr/bin/env node` since the second is present on both Linux and Mac? 

For anyone running into this problem, a quick fix is to change `#!/bin/env node` to `#!/usr/bin/env node` in `~/node_installation_location/node/vX.X.X/bin/nip06-cli`

On nvm this can be found in `~/.nvm/versions/node/vX.X.X/bin/nip06-cli`

**Comment by jaonoctus** [comment]
@matthewjablack could you test `nip06-cli@1.0.5-rc1` ?

**Comment by matthewjablack** [comment]
Works like a charm 👌

**Comment by jaonoctus** [comment]
Great, thank you for finding it!
